### ISSUE TITLE
When I click on the area in the picture, an error is reported

### ISSUE THREAD

**Issue by gaoxuxu110** [gaomingqi/Track-Anything#1]
Traceback (most recent call last):
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Deepfacelab\Deepface\Track-Anything\app.py", line 130, in sam_refine
    image=video_state["origin_images"][video_state["select_frame_number"]],
TypeError: 'NoneType' object is not subscriptable
![1](https://user-images.githubusercontent.com/52225349/232751809-e3233385-7f8b-4c8e-9f2c-ca668b24c826.png)
![2](https://user-images.githubusercontent.com/52225349/232751825-0af32f3e-aad9-46b2-8439-ff9264fa20da.png)

**Comment by memoryunreal** [comment]
It seems the video_state cannot obtain your uploaded video frames, please clone the recently committed version and try again.
