### ISSUE TITLE
mp4格式视频上传失败

### ISSUE THREAD

**Issue by weirui0430** [gaomingqi/Track-Anything#117]
你好，在可视化网页里，上传视频时，为什么有一些mp4格式视频上传失败呢？
报错：Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 222, in show_mask
    select_frame = video_state["origin_images"][video_state["select_frame_number"]]
TypeError: 'NoneType' object is not subscriptable

**Comment by zyz-code** [comment]
我是上传mp4视频大了就会失败，基本只能传个20秒的样子的视频，传着传着它就右边显示error了
