### ISSUE TITLE
TypeError: Row.__init__() got an unexpected keyword argument 'scale'

### ISSUE THREAD

**Issue by wwwffbf** [gaomingqi/Track-Anything#118]
python app.py --device cuda:0
this error happen:
Traceback (most recent call last):
  File "E:\SDiff\Track-Anything\app.py", line 506, in <module>
    with gr.Row(scale=0.4):
  File "E:\SDiff\Track-Anything\venv\lib\site-packages\gradio\component_meta.py", line 146, in wrapper
    return fn(self, **kwargs)
TypeError: Row.__init__() got an unexpected keyword argument 'scale'

**Comment by woshimark666** [comment]
I think this is due to gradio version too high.
I am using gradio==4.1.1 and I got the same error.
When I install the gradio==3.25.0 version I got another error like this.

Traceback (most recent call last):
  File "/home/mark/github/Track-Anything/app.py", line 393, in <module>
    with gr.Blocks() as iface:
  File "/home/mark/anaconda3/envs/tracker/lib/python3.10/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/home/mark/anaconda3/envs/tracker/lib/python3.10/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/home/mark/anaconda3/envs/tracker/lib/python3.10/site-packages/gradio_client/serializing.py", line 44, in input_api_info
    types = api_info.get("serialized_input", [api_info["info"]["type"]] * 2)  # type: ignore
KeyError: 'type'

**Comment by wwwffbf** [comment]
I've been working on it all day and haven't solved it. Let me know if you do.

**Comment by wwwffbf** [comment]
> I think this is due to gradio version too high. I am using gradio==4.1.1 and I got the same error. When I install the gradio==3.25.0 version I got another error like this.
> 
> Traceback (most recent call last): File "/home/mark/github/Track-Anything/app.py", line 393, in with gr.Blocks() as iface: File "/home/mark/anaconda3/envs/tracker/lib/python3.10/site-packages/gradio/blocks.py", line 1285, in **exit** self.config = self.get_config_file() File "/home/mark/anaconda3/envs/tracker/lib/python3.10/site-packages/gradio/blocks.py", line 1261, in get_config_file "input": list(block.input_api_info()), # type: ignore File "/home/mark/anaconda3/envs/tracker/lib/python3.10/site-packages/gradio_client/serializing.py", line 44, in input_api_info types = api_info.get("serialized_input", [api_info["info"]["type"]] * 2) # type: ignore KeyError: 'type'

You are right! Install gradio 3.48.0 can fix this.
