### ISSUE TITLE
Why did the 'scale' in the __init__ function cause an error during initialization?

### ISSUE THREAD

**Issue by WlbLucy** [gaomingqi/Track-Anything#124]
cmd error：

(trackany) E:\track_anything\Track-Anything>python app.py --device cuda:0
Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
load pretrained SPyNet...
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmediting/restorers/basicvsr/spynet_20210409-c6c1bd09.pth
Traceback (most recent call last):
  File "E:\track_anything\Track-Anything\app.py", line 431, in <module>
    with gr.Row(scale=0.4):
  File "C:\Users\Lucy\anaconda3\envs\trackany\lib\site-packages\gradio\component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: Row.__init__() got an unexpected keyword argument 'scale'

**Comment by WlbLucy** [comment]
这个项目支持的gradio tension是哪一个？我的是4.15.0但是报错了

**Comment by WlbLucy** [comment]
what's the gradio tension of this project?  Mine is 4.15.0 but it express ERROR.

**Comment by WlbLucy** [comment]
更新：把gradio版本降低后成功了。

**Comment by davitpapikyan** [comment]
> 更新：把gradio版本降低后成功了。

Please, can you elaborate? I din't understand your solution.

**Comment by davitpapikyan** [comment]
Solution: `pip install gradio==3.30`

**Comment by HanLingsgjk** [comment]
谢谢，对我很有帮助-爱来自瓷器

**Comment by balajidarur** [comment]
It is recommended to use 
`pip install gradio==3.39.0` . I have tried this based on #120

**Comment by wangyingli995** [comment]
> 更新：把gradio版本降低后成功了。

请问您降低到哪个版本之后运行成功了呀
