### ISSUE TITLE
Tracking Error

### ISSUE THREAD

**Issue by teidenzero** [gaomingqi/Track-Anything#13]
Hello,
I cloned the repo on my local machine but I get an ERROR on the GUI whenever I click TRACK

[ERROR:0@51.995] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'cv::CvCapture_Images::open'

Traceback (most recent call last):
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\gradio\routes.py", line 395, in run_predict    output = await app.get_blocks().process_api(
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "D:\Track-Anything\app.py", line 88, in get_frames_from_video
    image_size = (frames[0].shape[0],frames[0].shape[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\gradio\routes.py", line 395, in run_predict    output = await app.get_blocks().process_api(
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "D:\Track-Anything\app.py", line 221, in vos_tracking_video
    masks, logits, painted_images = model.generator(images=following_frames, template_mask=template_mask)
  File "D:\Track-Anything\track_anything.py", line 44, in generator
    mask, logit, painted_image = self.xmem.track(images[i], template_mask)
  File "C:\Users\Francesco\anaconda3\envs\stable_diffusion\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Track-Anything\tracker\base_tracker.py", line 82, in track
    probs, _ = self.tracker.step(frame_tensor, mask, labels)   # logits 2 (bg fg) H W
  File "D:\Track-Anything/tracker\inference\inference_core.py", line 102, in step
    value, hidden = self.network.encode_value(image, f16, self.memory.get_hidden(),
  File "D:\Track-Anything/tracker\model\network.py", line 75, in encode_value
    others = torch.cat([
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by teidenzero** [comment]
I just tried it on Ubuntu 22 and I get the same error

Traceback (most recent call last):
  File "/home/francesco/anaconda3/envs/trackAnything/lib/python3.9/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/francesco/anaconda3/envs/trackAnything/lib/python3.9/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/home/francesco/anaconda3/envs/trackAnything/lib/python3.9/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/francesco/anaconda3/envs/trackAnything/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/francesco/anaconda3/envs/trackAnything/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/francesco/anaconda3/envs/trackAnything/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/francesco/Track-Anything/app.py", line 221, in vos_tracking_video
    masks, logits, painted_images = model.generator(images=following_frames, template_mask=template_mask)
  File "/home/francesco/Track-Anything/track_anything.py", line 44, in generator
    mask, logit, painted_image = self.xmem.track(images[i], template_mask)
  File "/home/francesco/anaconda3/envs/trackAnything/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/francesco/Track-Anything/tracker/base_tracker.py", line 82, in track
    probs, _ = self.tracker.step(frame_tensor, mask, labels)   # logits 2 (bg fg) H W
  File "/home/francesco/Track-Anything/tracker/inference/inference_core.py", line 102, in step
    value, hidden = self.network.encode_value(image, f16, self.memory.get_hidden(),
  File "/home/francesco/Track-Anything/tracker/model/network.py", line 75, in encode_value
    others = torch.cat([
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by teidenzero** [comment]
My bad, I was using the software wrong. Closing the issue
