### ISSUE TITLE
When I run app.py, I encounter the following issue. How can I resolve it?

### ISSUE THREAD

**Issue by 1030zero** [gaomingqi/Track-Anything#147]
Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Traceback (most recent call last):
  File "D:\py\Track-Anything\app.py", line 385, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "D:\py\Track-Anything\track_anything.py", line 20, in __init__
    self.baseinpainter = BaseInpainter(self.e2fgvi_checkpoint, args.device)
  File "D:\py\Track-Anything\inpainter\base_inpainter.py", line 20, in __init__
    net = importlib.import_module('inpainter.model.e2fgvi_hq')
  File "E:\Anaconda\envs\trackany\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\py\Track-Anything\inpainter\model\e2fgvi_hq.py", line 9, in <module>
    from inpainter.model.modules.feat_prop import BidirectionalPropagation, SecondOrderDeformableAlignment
  File "D:\py\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\py\Track-Anything\inpainter\model\e2fgvi_hq.py", line 9, in <module>
    from inpainter.model.modules.feat_prop import BidirectionalPropagation, SecondOrderDeformableAlignment
  File "D:\py\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "D:\py\Track-Anything\inpainter\model\e2fgvi_hq.py", line 9, in <module>
    from inpainter.model.modules.feat_prop import BidirectionalPropagation, SecondOrderDeformableAlignment
  File "D:\py\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
    from inpainter.model.modules.feat_prop import BidirectionalPropagation, SecondOrderDeformableAlignment
  File "D:\py\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "D:\py\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "E:\Anaconda\envs\trackany\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "E:\Anaconda\envs\trackany\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "E:\Anaconda\envs\trackany\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
    from .active_rotated_filter import active_rotated_filter
  File "E:\Anaconda\envs\trackany\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
  File "E:\Anaconda\envs\trackany\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
    ext_module = ext_loader.load_ext(
  File "E:\Anaconda\envs\trackany\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
  File "E:\Anaconda\envs\trackany\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
    ext = importlib.import_module('mmcv.' + name)
  File "E:\Anaconda\envs\trackany\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

**Comment by KeenanWang** [comment]
你好，我也遇到了类似的问题，应该是mmcv与torch的版本兼容出问题了。
由于作者把requirements.txt中的版本去掉了，导致pip安装的时候会自动安装最新的版本，这样子的话可能导致mmcv与torch版本不匹配。具体可以参考[通过pip安装mmcv](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip)

<img width="899" height="380" alt="Image" src="https://github.com/user-attachments/assets/da1f387b-7711-4d9b-862f-bccbd792dffe" />
希望对你有用！
