### ISSUE TITLE
Demo won't launch.

### ISSUE THREAD

**Issue by hoolswelsh** [gaomingqi/Track-Anything#18]
Holly@HOLLY MINGW64 ~/Documents/Track-Anything (master)
$ python app.py --device cuda:0
C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Traceback (most recent call last):
  File "C:\Users\Holly\Documents\Track-Anything\app.py", line 372, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "C:\Users\Holly\Documents\Track-Anything\track_anything.py", line 20, in __init__
    self.baseinpainter = BaseInpainter(self.e2fgvi_checkpoint, args.device)
  File "C:\Users\Holly\Documents\Track-Anything\inpainter\base_inpainter.py", line 20, in __init__
    net = importlib.import_module('inpainter.model.e2fgvi_hq')
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Holly\Documents\Track-Anything\inpainter\model\e2fgvi_hq.py", line 9, in <module>
    from inpainter.model.modules.feat_prop import BidirectionalPropagation, SecondOrderDeformableAlignment
  File "C:\Users\Holly\Documents\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\Holly\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

**Comment by memoryunreal** [comment]
It seems mmcv installation problem. Please try to git pull the latest commit. The mmcv installation has been changed. Refer to #14

**Comment by xzhou29** [comment]
pip install mmcv-full
