### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by marquus2** [gaomingqi/Track-Anything#2]
I think it's a external problem, but someone know any solution? 
Nvidia/cuda drivers updated. 

E:\Segment\Track-Anything>app.py
download checkpoints ......
download successfully!
download checkpoints ......
download successfully!
Initializing BaseSegmenter to cuda:4
Traceback (most recent call last):
  File "E:\Segment\Track-Anything\app.py", line 200, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, args)
  File "E:\Segment\Track-Anything\track_anything.py", line 14, in __init__
    self.samcontroler = SamControler(sam_checkpoint, args.sam_model_type, args.device)
  File "E:\Segment\Track-Anything\tools\interact_tools.py", line 37, in __init__
    self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device)
  File "E:\Segment\Track-Anything\tools\base_segmenter.py", line 26, in __init__
    self.model.to(device=self.device)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 990, in to
    return self._apply(convert)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 642, in _apply
    module._apply(fn)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 642, in _apply
    module._apply(fn)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 642, in _apply
    module._apply(fn)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 665, in _apply
    param_applied = fn(param)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 988, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by memoryunreal** [comment]
Sorry, please clone the repo again or manually comment on these three lines of code, and assign values to args.port (default 6080), args.device (default cuda:0), or use the default values. https://github.com/gaomingqi/Track-Anything/blob/78ff72de87857c24feb21651f05c3d381efd631e/app.py#L196-L198

**Comment by marquus2** [comment]
Thanks, works changing # args.device = "cuda:4" to "cuda:0", I dont know why 4 was the default
