### ISSUE TITLE
Tutorial install Track-Anything for video in Windows

### ISSUE THREAD

**Issue by D-Mad** [gaomingqi/Track-Anything#23]
https://youtu.be/MQJ4LMLXm30

**Comment by memoryunreal** [comment]
Thanks for your information!

**Comment by WelschCode** [comment]
Building wheels for collected packages: mmcv
  Building wheel for mmcv (setup.py) ... |
Is hanging for some reason. 

I used `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117` already satisfied that. 
`Requirement already satisfied: six>=1.5 in c:\users\12138\miniconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (1.16.0)
Building wheels for collected packages: mmcv
  Building wheel for mmcv (setup.py) ... /`

Did get this error 
`(base) E:\AI\XMem-main\XMem-main\Track-Anything>python app.py --device cuda:0
Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Traceback (most recent call last):
  File "E:\AI\XMem-main\XMem-main\Track-Anything\app.py", line 326, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "E:\AI\XMem-main\XMem-main\Track-Anything\track_anything.py", line 15, in __init__
    self.baseinpainter = BaseInpainter(e2fgvi_checkpoint, args.device)
  File "E:\AI\XMem-main\XMem-main\Track-Anything\inpainter\base_inpainter.py", line 18, in __init__
    net = importlib.import_module('inpainter.model.e2fgvi_hq')
  File "C:\Users\12138\MiniConda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\AI\XMem-main\XMem-main\Track-Anything\inpainter\model\e2fgvi_hq.py", line 9, in <module>
    from inpainter.model.modules.feat_prop import BidirectionalPropagation, SecondOrderDeformableAlignment
  File "E:\AI\XMem-main\XMem-main\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "C:\Users\12138\MiniConda3\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from mmcv.utils import IS_MLU_AVAILABLE
ImportError: cannot import name 'IS_MLU_AVAILABLE' from 'mmcv.utils' (C:\Users\12138\MiniConda3\lib\site-packages\mmcv\utils\__init__.py)
`

**Comment by WelschCode** [comment]
Thank you for the help! It does throw an error if you use more than one mask or try to mask and then paint even with the ratio all the way at the bottom for some reason. Hoping for a resolution on that! :)
