### ISSUE TITLE
This error occurs when I click on " Tracking"

### ISSUE THREAD

**Issue by gaoxuxu110** [gaomingqi/Track-Anything#3]
```
Traceback (most recent call last):
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\Lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\Lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\Lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Deepfacelab\Deepface\Track-Anything\app.py", line 149, in vos_tracking_video
    masks, logits, painted_images = model.generator(images=following_frames, template_mask=template_mask)
  File "H:\Deepfacelab\Deepface\Track-Anything\track_anything.py", line 46, in generator
    mask, logit, painted_image = self.xmem.track(images[i], template_mask)
  File "H:\Deepfacelab\Deepface\Track-Anything\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Deepfacelab\Deepface\Track-Anything\tracker\base_tracker.py", line 81, in track
    probs, _ = self.tracker.step(frame_tensor, mask, labels)   # logits 2 (bg fg) H W
  File "H:\Deepfacelab\Deepface\Track-Anything/tracker\inference\inference_core.py", line 113, in step
    return unpad(pred_prob_with_bg, self.pad), None
  File "H:\Deepfacelab\Deepface\Track-Anything/tracker\util\tensor_util.py", line 35, in unpad
    if len(img.shape) == 4:
AttributeError: 'NoneType' object has no attribute 'shape'

```

**Comment by gaomingqi** [comment]
Hello, it seems no mask is provided as the template. Before clicking tracking, please select the template via Template Select, as illustrate in our demo video. Thanks.

**Comment by gaoxuxu110** [comment]
Thank you for your reply!!!




当幸福来敲门
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gaomingqi/Track-Anything"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gaomingqi/Track-Anything] This error occurs when I click on " Tracking" (Issue #3)





 
Hello, it seems no mask is provided as the template. Before clicking tracking, please select the template via Template Select, as illustrate in our demo video. Thanks.

**Comment by lmst2** [comment]
hi I have the same issue, I have added 2 masks, will this happen because all objects are gone in the scene?
