### ISSUE TITLE
can this run in macos m1 pro(mps)

### ISSUE THREAD

**Issue by ImTopz** [gaomingqi/Track-Anything#33]
as what i questioned, i don't have Nvidia device,just mps

**Comment by memoryunreal** [comment]
Refer to #20 , we haven't tested it on the M1/M2 device. Maybe one solution is to duplicate the  [Huggingface space](https://huggingface.co/spaces/watchtowerss/Track-Anything?duplicate=true) with T4 small (0.6$/h).

**Comment by iamcos** [comment]
Its not working with apple m1 max.


(venv) cosmos@Cosmoss-Macbook-Pro Track-Anything % python app.py
Initializing BaseSegmenter to cpu
Traceback (most recent call last):
  File "/Users/cosmos/Documents/GitHub/Track-Anything/app.py", line 383, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "/Users/cosmos/Documents/GitHub/Track-Anything/track_anything.py", line 19, in __init__
    self.xmem = BaseTracker(self.xmem_checkpoint, device=args.device)
  File "/Users/cosmos/Documents/GitHub/Track-Anything/tracker/base_tracker.py", line 32, in __init__
    network = XMem(config, xmem_checkpoint).to(device).eval()
  File "/Users/cosmos/Documents/GitHub/Track-Anything/tracker/model/network.py", line 24, in __init__
    model_weights = self.init_hyperparameters(config, model_path, map_location)
  File "/Users/cosmos/Documents/GitHub/Track-Anything/tracker/model/network.py", line 145, in init_hyperparameters
    model_weights = torch.load(model_path, map_location=map_location)
  File "/Users/cosmos/Documents/GitHub/Track-Anything/venv/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/cosmos/Documents/GitHub/Track-Anything/venv/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/Users/cosmos/Documents/GitHub/Track-Anything/venv/lib/python3.10/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/Users/cosmos/Documents/GitHub/Track-Anything/venv/lib/python3.10/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/Users/cosmos/Documents/GitHub/Track-Anything/venv/lib/python3.10/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/Users/cosmos/Documents/GitHub/Track-Anything/venv/lib/python3.10/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/cosmos/Documents/GitHub/Track-Anything/venv/lib/python3.10/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
