### ISSUE TITLE
Getting an error called: "Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by HappyClownn** [gaomingqi/Track-Anything#35]
app.py --device cuda:0

Initializing BaseSegmenter to cuda:0
Traceback (most recent call last):
  File "C:\Users\Happy\Desktop\Git\Track-Anything\app.py", line 383, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Happy\Desktop\Git\Track-Anything\track_anything.py", line 18, in __init__
    self.samcontroler = SamControler(self.sam_checkpoint, args.sam_model_type, args.device)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Happy\Desktop\Git\Track-Anything\tools\interact_tools.py", line 37, in __init__
    self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Happy\Desktop\Git\Track-Anything\tools\base_segmenter.py", line 26, in __init__
    self.model.to(device=self.device)
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Happy\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I don't know how to fix this, can anyone help?

**Comment by finnschi** [comment]
just install pytorch again with cuda enabled , I use latest 11.8 or whatever that was

**Comment by HappyClownn** [comment]
> just install pytorch again with cuda enabled , I use latest 11.8 or whatever that was

This worked, thank you!
