### ISSUE TITLE
does not run although all requirements fullfilled

### ISSUE THREAD

**Issue by TanvirHafiz** [gaomingqi/Track-Anything#41]
the console givesme this messages:

Initializing BaseSegmenter to cuda:0
Traceback (most recent call last):
  File "G:\TrackAnything\Track-Anything\app.py", line 384, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "G:\TrackAnything\Track-Anything\track_anything.py", line 18, in __init__
    self.samcontroler = SamControler(self.sam_checkpoint, args.sam_model_type, args.device)
  File "G:\TrackAnything\Track-Anything\tools\interact_tools.py", line 37, in __init__
    self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device)
  File "G:\TrackAnything\Track-Anything\tools\base_segmenter.py", line 26, in __init__
    self.model.to(device=self.device)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\Tanvir\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

not sure whats going on and whats the solution. it seems something is missing.

**Comment by PedroRossa** [comment]
I'm receiving the same error:

E:\Python\lib\site-packages\torchvision\models\detection\anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:77.)
  device: torch.device = torch.device("cpu"),
Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
Traceback (most recent call last):
  File "E:\Track-Anything\app.py", line 383, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "E:\Track-Anything\track_anything.py", line 20, in __init__
    self.baseinpainter = BaseInpainter(self.e2fgvi_checkpoint, args.device)
  File "E:\Track-Anything\inpainter\base_inpainter.py", line 20, in __init__
    net = importlib.import_module('inpainter.model.e2fgvi_hq')
  File "E:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Track-Anything\inpainter\model\e2fgvi_hq.py", line 9, in <module>
    from inpainter.model.modules.feat_prop import BidirectionalPropagation, SecondOrderDeformableAlignment
  File "E:\Track-Anything\inpainter\model\modules\feat_prop.py", line 7, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "E:\Python\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "E:\Python\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "E:\Python\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "E:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

**Comment by Abijeet123** [comment]
Maybe you can refer these:

https://github.com/open-mmlab/mmtracking/issues/482

https://github.com/open-mmlab/mmcv/issues/1594

Please update me if that works

**Comment by TanvirHafiz** [comment]
SO i need to install MMCV (no idea what that is). should it not have been automatically installed alongside track anything as dependancies?

**Comment by aboharbf** [comment]
I got the error described in the OP, and upon trying @Abijeet123's solution, ended up with an issue related to wheels - same issue going on here seemingly - https://github.com/open-mmlab/mmcv/issues/1055
