### ISSUE TITLE
Error during the installion

### ISSUE THREAD

**Issue by Zixuan-Xu-GodVision** [gaomingqi/Track-Anything#42]
When I followed the instruction to install all the requirements, I still got some problems as follow:
Initializing BaseSegmenter to cuda:0
Traceback (most recent call last):
  File "E:\Sydney University\CVProject\Project\Track_Anything\Track-Anything-master\app.py", line 343, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "E:\Sydney University\CVProject\Project\Track_Anything\Track-Anything-master\track_anything.py", line 13, in __init__
    self.samcontroler = SamControler(sam_checkpoint, args.sam_model_type, args.device)
  File "E:\Sydney University\CVProject\Project\Track_Anything\Track-Anything-master\tools\interact_tools.py", line 37, in __init__
    self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device)
  File "E:\Sydney University\CVProject\Project\Track_Anything\Track-Anything-master\tools\base_segmenter.py", line 25, in __init__
    self.model = sam_model_registry[model_type](checkpoint=SAM_checkpoint)
  File "D:\Anaconda\envs\Track_Anything\lib\site-packages\segment_anything\build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "D:\Anaconda\envs\Track_Anything\lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "D:\Anaconda\envs\Track_Anything\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\Anaconda\envs\Track_Anything\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Is there anyone meet the same problem and solve it?

**Comment by gaomingqi** [comment]
Hello, it seems the pre-trained SAM model is not downloaded completely. You can clear cached files in Track-Anyting/checkpoints and try again. Thanks.

**Comment by Zixuan-Xu-GodVision** [comment]
> Hello, it seems the pre-trained SAM model is not downloaded completely. You can clear cached files in Track-Anyting/checkpoints and try again. Thanks.

Yeah it works, thank you so much!
But I got another problem when I run the app and get the video info,  I was using the example video , it shows : Something went wrong  Expecting value: line 1 column 1 (char 0) , as shown in the fig

![1](https://user-images.githubusercontent.com/100177339/235442182-1cc09a82-7083-4ce4-9018-35abc5803728.png)

Is there any specific video forms needed ?

**Comment by PedroRossa** [comment]
I have the same error, but even deleting the checkpoints I Still receiving the same errors.

**Comment by Zixuan-Xu-GodVision** [comment]
I think you could try to download the model file in checkpoints directly on the official website, the URL can be found on the app.py
________________________________
发件人: Pedro Rossa ***@***.***>
发送时间: 2023年5月2日 3:09
收件人: gaomingqi/Track-Anything ***@***.***>
抄送: Zixuan Xu ***@***.***>; Author ***@***.***>
主题: Re: [gaomingqi/Track-Anything] Error during the installion (Issue #42)


I have the same error, but even deleting the checkpoints I Still receiving the same errors.

―

**Comment by KnSun99** [comment]
![image](https://user-images.githubusercontent.com/123467428/236229615-a4062d41-9587-4b08-8df8-5855ed323ecd.png)

![image](https://user-images.githubusercontent.com/123467428/236229755-982fc1d3-0f4d-47df-8689-d71d9574a439.png)

There should be no missing model files, but this problem still occurs

**Comment by Zixuan-Xu-GodVision** [comment]
> ![image](https://user-images.githubusercontent.com/123467428/236229615-a4062d41-9587-4b08-8df8-5855ed323ecd.png)
> 
> ![image](https://user-images.githubusercontent.com/123467428/236229755-982fc1d3-0f4d-47df-8689-d71d9574a439.png)
> 
> There should be no missing model files, but this problem still occurs

Do you fix this? I still troubled by this error.

**Comment by KnSun99** [comment]
I'm trying to figure it out, too
