### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by sisyphus229** [gaomingqi/Track-Anything#59]
Initializing BaseSegmenter to cuda:0
Traceback (most recent call last):
  File "D:\pythonProject\Track-Anything-master\app.py", line 383, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "D:\pythonProject\Track-Anything-master\track_anything.py", line 18, in __init__
    self.samcontroler = SamControler(self.sam_checkpoint, args.sam_model_type, args.device)
  File "D:\pythonProject\Track-Anything-master\tools\interact_tools.py", line 37, in __init__
    self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device)
  File "D:\pythonProject\Track-Anything-master\tools\base_segmenter.py", line 25, in __init__
    self.model = sam_model_registry[model_type](checkpoint=SAM_checkpoint)
  File "D:\anaconda\envs\my_pytorch\lib\site-packages\segment_anything\build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "D:\anaconda\envs\my_pytorch\lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "D:\anaconda\envs\my_pytorch\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\anaconda\envs\my_pytorch\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

进程已结束,退出代码1

What is this problem?

**Comment by gaomingqi** [comment]
Hello, it seems pre-trained weights for SAM are not downloaded completely. Please clear the cached files in checkpoints folder and try again. Thanks.

**Comment by sisyphus229** [comment]
> Hello, it seems pre-trained weights for SAM are not downloaded completely. Please clear the cached files in checkpoints folder and try again. Thanks.

yes, I just solved that problem, too. Thank you very much.  And then I want to ask you how much memory i need to run the TAM, which always say is out of memory.

**Comment by gaomingqi** [comment]
Hello, please check our previous discussions for more details about memory: https://github.com/gaomingqi/Track-Anything/issues/4#issuecomment-1522055186 (run TAM for tracking), https://github.com/gaomingqi/Track-Anything/issues/4#issuecomment-1528198165 (run TAM for inpainting). Thanks.

**Comment by sisyphus229** [comment]
> Hello, please check our previous discussions for more details about memory: [#4 (comment)](https://github.com/gaomingqi/Track-Anything/issues/4#issuecomment-1522055186) (run TAM for tracking), [#4 (comment)](https://github.com/gaomingqi/Track-Anything/issues/4#issuecomment-1528198165) (run TAM for inpainting). Thanks.

Hello, I have a new problem. When I opened this url(Running on local URL:  http://0.0.0.0:6080
) I encountered the problem as shown in the figure. I would like to ask what caused this?
![image](https://user-images.githubusercontent.com/80449655/236998879-909e62df-165f-4fc4-aea5-92578067207d.png)

Then, this problem occurred when I was using a linux server.

Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
load pretrained SPyNet...
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmediting/restorers/basicvsr/spynet_20210409-c6c1bd09.pth
/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 0.4}
  warnings.warn(
/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Video, please remove them: {'autosize': True}
  warnings.warn(
/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/components.py:164: UserWarning: Unknown style parameter: height
  warnings.warn(f"Unknown style parameter: {key}")
Traceback (most recent call last):
  File "/home/ubuntu/wyz/Track-Anything/app.py", line 588, in <module>
    gr.Examples(
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio_client/serializing.py", line 41, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'

Finally, I think your work is excellent and I'm personally very interested!!
