### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by sisyphus229** [gaomingqi/Track-Anything#61]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/gradio/blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/wyz/app.py", line 116, in get_frames_from_video
    model.samcontroler.sam_controler.set_image(video_state["origin_images"][0])
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/wyz/tools/base_segmenter.py", line 38, in set_image
    self.predictor.set_image(image)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/segment_anything/predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/segment_anything/predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/segment_anything/modeling/image_encoder.py", line 107, in forward
    x = self.patch_embed(x)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/segment_anything/modeling/image_encoder.py", line 392, in forward
    x = self.proj(x)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/anaconda3/envs/wyz/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

Hello！ Can you help me solve this problem? I haven't found a suitable solution yet.

**Comment by Mahmoud-Ali-FCIS** [comment]
Same issue here. Do you solve it? @sisyphus229
