### ISSUE TITLE
Inpainting not working - ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by PsychoSmiley** [gaomingqi/Track-Anything#63]
windows os
I did try
-[Fix1](https://github.com/gaomingqi/Track-Anything/issues/35)
```
pip uninstall -y torch torchvision torchaudio
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 --upgrade
```

-[Fix2](https://github.com/gaomingqi/Track-Anything/issues/45#issuecomment-1538044537)
`pip install --upgrade gradio`
```
...
Running on local URL:  http://0.0.0.0:6080

To create a public link, set `share=True` in `launch()`.
Tracking image: 100%|██████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 27.34it/s]
For generating this tracking result, inference times: 1, click times: 1, positive: 1, negative: 0
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\PsychoSmiley\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\PsychoSmiley\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\PsychoSmiley\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\PsychoSmiley\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Inpainting image:   0%|                                                                         | 0/10 [00:00<?, ?it/s]D:\main\program\AI\Track-Anything\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Inpainting image:   0%|                                                                         | 0/10 [00:00<?, ?it/s]
```

**Comment by PsychoSmiley** [comment]
no, resize ration of 0.1, 10 first frame on sample video with 24GB VRAM.
