### ISSUE TITLE
Nothing worked after installation

### ISSUE THREAD

**Issue by XinyueZ** [gaomingqi/Track-Anything#76]
Hey guys, can you help?

I just got 

```bash
Traceback (most recent call last):
  File "/workspace/app.py", line 391, in <module>
    with gr.Blocks() as iface:
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/gradio_client/serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'
```
thanks

**Comment by merecesarchviz** [comment]
same here after install it the surprise a lot of errors! any tip to solve it

![image](https://github.com/gaomingqi/Track-Anything/assets/79140456/7bd60a4b-f828-4f9d-b730-4ddff216c5e0)

**Comment by jin-eld** [comment]
I can't tell if this is related to your error, but keep in mind that `--device` does not work, it's hardcoded to `cuda:3` in the sources:
https://github.com/gaomingqi/Track-Anything/blob/e6e159273790974e04eeea6673f1f93c035005fc/app.py#L381C16-L381C21

**Comment by merecesarchviz** [comment]
> I can't tell if this is related to your error, but keep in mind that `--device` does not work, it's hardcoded to `cuda:3` in the sources: https://github.com/gaomingqi/Track-Anything/blob/e6e159273790974e04eeea6673f1f93c035005fc/app.py#L381C16-L381C21

but i try to run without --device and i got the same error! also i try to edit that line and the same errors!

**Comment by Colmar-zlicheng** [comment]
I just meet the same issue, but I solve it by:
```
pip uninstall gradio_client && pip install gradio_client==0.1.0
```
I found this solution in https://github.com/oobabooga/text-generation-webui/issues/1855#issuecomment-1537206165
