### ISSUE TITLE
ImportError: cannot import name 'SpaceStage' from 'huggingface_hub' (unknown location)

### ISSUE THREAD

**Issue by Sequential-circuits** [gaomingqi/Track-Anything#8]
(base) root@185:~/Track-Anything# python app.py --device cuda:0 --sam_model_type vit_h --port 80
Traceback (most recent call last):
  File "/root/Track-Anything/app.py", line 1, in <module>
    import gradio as gr
  File "/root/anaconda3/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/root/anaconda3/lib/python3.10/site-packages/gradio/components.py", line 34, in <module>
    from gradio_client import utils as client_utils
  File "/root/anaconda3/lib/python3.10/site-packages/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/root/anaconda3/lib/python3.10/site-packages/gradio_client/client.py", line 21, in <module>
    from huggingface_hub import SpaceStage
ImportError: cannot import name 'SpaceStage' from 'huggingface_hub' (unknown location)

**Comment by memoryunreal** [comment]
Sorry, we are unable to reproduce your issue. For problems related to site-packages, it is likely caused by package version conflicts. Please try creating a new environment or attempt pip install -U huggingface_hub.
